apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: tinywebsite
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: tinywebsite
        tier: frontend
    spec:
      containers:
      - name: tinywebsite
        image: irnlogic/djangotinyurl:1.0
        resources:
          requests:
            cpu: 1
            memory: 128Mi
        ports:
        - containerPort: 8001
