apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        tier: backend
    spec:
      containers:
      - name: master
        image: irnlogic/postgres:latest  # or just image: redis
        resources:
          requests:
            cpu: 1
            memory: 128Mi
        ports:
        - containerPort: 5432
        envFrom:
            - configMapRef:
                name: postgres-config
        volumeMounts:
            - mountPath: /var/lib/postgresql/
              name: postgredb                
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-disk                
