version: '3'

services:
  redis:
    build: ./redis
    ports:
      - 6379:6379

  postgres:
    build: ./db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  client:
    build: ./client
    ports:
      - 3000:8001
    depends_on:
      - redis
      - postgres
